COMPANY = {
    "name": "Wolke Systems",
    "tagline": "Internal enterprise identity playground",
    "stage": "Scope II - Internal Applications Ecosystem",
    "identity_note": "Authentication and authorization are intentionally not implemented here.",
}

DEPARTMENTS = [
    {
        "id": "engineering",
        "name": "Engineering",
        "teams": ["Backend", "Frontend", "Platform"],
        "headcount": 42,
        "lead": "Mira Shah",
    },
    {
        "id": "finance",
        "name": "Finance",
        "teams": ["Accounting", "Budgeting", "Payroll"],
        "headcount": 14,
        "lead": "Owen Patel",
    },
    {
        "id": "hr",
        "name": "Human Resources",
        "teams": ["People Ops", "Recruiting", "Benefits"],
        "headcount": 11,
        "lead": "Anika Rao",
    },
    {
        "id": "security",
        "name": "Security",
        "teams": ["AppSec", "IAM", "Incident Response"],
        "headcount": 9,
        "lead": "Dev Verma",
    },
    {
        "id": "operations",
        "name": "Operations",
        "teams": ["Facilities", "Vendor Ops", "IT Support"],
        "headcount": 18,
        "lead": "Leah Thomas",
    },
]

USERS = [
    {
        "id": "u-1001",
        "name": "Mira Shah",
        "role": "Engineering Manager",
        "department": "Engineering",
        "type": "Manager",
        "status": "Active",
        "location": "Bengaluru",
    },
    {
        "id": "u-1002",
        "name": "Owen Patel",
        "role": "Finance Manager",
        "department": "Finance",
        "type": "Manager",
        "status": "Active",
        "location": "Mumbai",
    },
    {
        "id": "u-1003",
        "name": "Anika Rao",
        "role": "HR Business Partner",
        "department": "Human Resources",
        "type": "Employee",
        "status": "Active",
        "location": "Pune",
    },
    {
        "id": "u-1004",
        "name": "Dev Verma",
        "role": "Security Administrator",
        "department": "Security",
        "type": "System Administrator",
        "status": "Active",
        "location": "Hyderabad",
    },
    {
        "id": "u-1005",
        "name": "Nora Iyer",
        "role": "Platform Engineer",
        "department": "Engineering",
        "type": "Employee",
        "status": "Active",
        "location": "Remote",
    },
    {
        "id": "u-1006",
        "name": "Sam Gill",
        "role": "Data Analyst",
        "department": "Operations",
        "type": "Contractor",
        "status": "Contract ends in 21 days",
        "location": "Delhi",
    },
]

PORTALS = [
    {
        "id": "hr",
        "name": "HR Portal",
        "summary": "Employee lifecycle, manager approvals, onboarding, and people operations.",
        "department": "Human Resources",
        "accent": "#c2410c",
        "required_context": ["employee_status", "manager_relationship", "department"],
        "primary_roles": ["HR Employee", "Manager"],
        "permissions": ["view_employee_profile", "start_onboarding", "approve_time_off", "manage_benefits"],
        "metrics": [
            {"label": "Open onboarding cases", "value": "12"},
            {"label": "Pending manager approvals", "value": "7"},
            {"label": "Contractors expiring", "value": "3"},
        ],
        "records": [
            {"title": "Nora Iyer", "meta": "Platform Engineer", "status": "Benefits update pending"},
            {"title": "Sam Gill", "meta": "Contractor", "status": "Renewal review needed"},
            {"title": "Campus intern batch", "meta": "8 people", "status": "Onboarding next Monday"},
        ],
    },
    {
        "id": "finance",
        "name": "Finance Dashboard",
        "summary": "Budget monitoring, payroll review, reimbursements, and finance approvals.",
        "department": "Finance",
        "accent": "#047857",
        "required_context": ["finance_role", "approval_limit", "department"],
        "primary_roles": ["Finance Analyst", "Finance Manager"],
        "permissions": ["view_reports", "export_csv", "approve_budget", "modify_payroll"],
        "metrics": [
            {"label": "Monthly spend", "value": "$842K"},
            {"label": "Budget approvals", "value": "5"},
            {"label": "Payroll exceptions", "value": "2"},
        ],
        "records": [
            {"title": "Engineering cloud budget", "meta": "$96K requested", "status": "Manager approval required"},
            {"title": "Q2 travel reimbursements", "meta": "31 claims", "status": "Ready for review"},
            {"title": "Payroll adjustment", "meta": "2 employees", "status": "Restricted action"},
        ],
    },
    {
        "id": "git",
        "name": "Internal Git Service",
        "summary": "Engineering repositories, pull requests, deployment keys, and code ownership.",
        "department": "Engineering",
        "accent": "#2563eb",
        "required_context": ["engineering_team", "repo_membership", "contractor_status"],
        "primary_roles": ["Engineer", "Engineering Manager", "Security Reviewer"],
        "permissions": ["read_repo", "push_branch", "merge_pr", "manage_deploy_keys"],
        "metrics": [
            {"label": "Active repositories", "value": "48"},
            {"label": "Open pull requests", "value": "26"},
            {"label": "Protected branches", "value": "19"},
        ],
        "records": [
            {"title": "identity-gateway", "meta": "Platform", "status": "3 PRs waiting"},
            {"title": "payroll-service", "meta": "Finance systems", "status": "Security review required"},
            {"title": "contractor-access", "meta": "IAM tooling", "status": "Deploy key rotates today"},
        ],
    },
    {
        "id": "admin",
        "name": "Admin Console",
        "summary": "Organization administration, application inventory, system settings, and access operations.",
        "department": "Security",
        "accent": "#7c3aed",
        "required_context": ["admin_role", "break_glass_state", "audit_reason"],
        "primary_roles": ["System Administrator", "Security Administrator"],
        "permissions": ["manage_users", "register_application", "invalidate_sessions", "assign_temporary_access"],
        "metrics": [
            {"label": "Managed apps", "value": "5"},
            {"label": "Temporary grants", "value": "4"},
            {"label": "Audit events today", "value": "183"},
        ],
        "records": [
            {"title": "Finance Dashboard client", "meta": "Internal app", "status": "OIDC prep pending"},
            {"title": "Contractor access policy", "meta": "Security", "status": "Expires automatically"},
            {"title": "Session invalidation drill", "meta": "IAM", "status": "Scheduled Friday"},
        ],
    },
    {
        "id": "analytics",
        "name": "Analytics Platform",
        "summary": "Cross-department reporting, operational visibility, and governance dashboards.",
        "department": "Operations",
        "accent": "#0891b2",
        "required_context": ["report_scope", "data_classification", "department_visibility"],
        "primary_roles": ["Manager", "Data Analyst", "Security Reviewer"],
        "permissions": ["view_department_metrics", "view_cross_department_metrics", "export_reports", "inspect_audit_trends"],
        "metrics": [
            {"label": "Dashboards", "value": "17"},
            {"label": "Restricted datasets", "value": "6"},
            {"label": "Exports this week", "value": "44"},
        ],
        "records": [
            {"title": "Department access matrix", "meta": "Governance", "status": "Updated hourly"},
            {"title": "Failed login trend", "meta": "Security", "status": "Waiting for auth data"},
            {"title": "Contractor system usage", "meta": "Operations", "status": "Needs identity feed"},
        ],
    },
]
